//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoList_Project.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Uye
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Uye()
        {
            this.Tbl_ToDo = new HashSet<Tbl_ToDo>();
        }
    
        public int ID { get; set; }
        public string AD { get; set; }
        public string SOYAD { get; set; }
        public string KULLANICIADI { get; set; }
        public string MAIL { get; set; }
        public string SIFRE { get; set; }
        public string TELEFON { get; set; }
        public Nullable<int> HAREKET { get; set; }
    
        public virtual Tbl_Islem Tbl_Islem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_ToDo> Tbl_ToDo { get; set; }
    }
}
