//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoList_Project.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Islem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Islem()
        {
            this.Tbl_ToDo = new HashSet<Tbl_ToDo>();
            this.Tbl_Uye = new HashSet<Tbl_Uye>();
        }
    
        public int ID { get; set; }
        public Nullable<int> UYE { get; set; }
        public Nullable<int> ISLEM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_ToDo> Tbl_ToDo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Uye> Tbl_Uye { get; set; }
    }
}
